### ISSUE TITLE
ResolutionError: The key 'sf.security.helmet.actions' is not bound to any value in context RequestContext-gY0uhFUWRMyqzs2bXcksWw-3

### ISSUE THREAD

**Issue by surabhidwivedi** [sourcefuse/loopback4-helmet#24]
**Describe the bug**
While putting the following code in sequence.ts file 

export class MySequence implements SequenceHandler {

  @inject(SequenceActions.INVOKE_MIDDLEWARE, {optional: true})
  protected invokeMiddlewareN: InvokeMiddleware = () => false;

  constructor(
    @inject(SequenceActions.FIND_ROUTE) protected findRoute: FindRoute,
    @inject(SequenceActions.PARSE_PARAMS) protected parseParams: ParseParams,
    @inject(SequenceActions.INVOKE_METHOD) protected invoke: InvokeMethod,
    @inject(SequenceActions.SEND) public send: Send,
    @inject(SequenceActions.REJECT) public reject: Reject,
    @inject(HelmetSecurityBindings.HELMET_SECURITY_ACTION)
    protected helmetAction: HelmetAction,
  ) { }

  async handle(context: RequestContext) {
    const requestTime = Date.now();
    try {
      const {request, response} = context;
      const route = this.findRoute(request);
      const args = await this.parseParams(request, route);

      // Helmet Action here
      //await this.helmetAction(request, response);

      const result = await this.invoke(route, args);
      this.send(response, result);
    } catch (err) {
      console.log();
    } finally {
      console.log();
    }
  }
}

I am getting an error 

"Resolution Error: The key 'sf.security.helmet.actions' is not bound to any value in context RequestContext-gY0uhFUWRMyqzs2bXcksWw-3"

I want to use helmet for Strict Transport Security Policy and Cross Origin Resource Sharing Configuration, but I am stuck here only.

Please help me, I am new to loop back. Thank you in advance.

**Comment by AnkurBansalSF** [comment]
I think you have not added Loopback4HelmetComponent to your applications.
this.component(Loopback4HelmetComponent);

**Comment by surabhidwivedi** [comment]
Thanks for response, but whenever I try to add  this.component(Loopback4HelmetComponent); I am getting 
Argument of type 'typeof Loopback4HelmetComponent' is not assignable to parameter of type 'Constructor<Component>'.
  Types of construct signatures are incompatible.
    Type 'new () => Loopback4HelmetComponent' is not assignable to type 'new (...args: any[]) => Component'.
      Construct signature return types 'Loopback4HelmetComponent' and 'Component' are incompatible.
        The types of 'bindings' are incompatible between these types.
          Type 'import("/../node_modules

**Comment by AnkurBansalSF** [comment]
This error is due to version mismatch.
To fix that:
1. switch to @loopback/cli v3, node v16 and update your project dependencies. (if using loopback4-helmet v4)
2. or, rollback to an older version of loopback4-helmet.

**Comment by surabhidwivedi** [comment]
Thanks for your reply. How can rollback to an older version of loopback4-helmet ??

**Comment by AnkurBansalSF** [comment]
https://stackoverflow.com/questions/15890958/how-to-install-a-previous-exact-version-of-a-npm-package

**Comment by surabhidwivedi** [comment]
Thank you for your reply, but I am still getting same error. 

I installed older version of helmet. npm install loopback4-helmet@3.0.0

**Comment by Rahulgojra** [comment]
Hi @surabhidwivedi ,
I am also getting the same error, Have you found any solution for this problem?

**Comment by yeshamavani** [comment]
@surabhidwivedi  please use the latest version of @loopback/context -- 5.0.7

**Comment by Rahulgojra** [comment]
Hi @yeshamavani 
I am using these version for loopback
"@loopback/boot": "^3.4.2",
    "@loopback/context": "^5.0.7",
    "@loopback/core": "^2.16.2",
    "@loopback/repository": "^3.7.1",
    "@loopback/rest": "^10.0.0",
    "@loopback/rest-explorer": "^3.3.2",
    "@loopback/service-proxy": "^3.2.2",
 "loopback4-helmet": "^4.2.0",

@loopback/contextn and loopback4-helmet have the latest version but still I am getting the same error

**Comment by AnkurBansalSF** [comment]
Your other loopback dependencies also need to be updated
Please try again after running "lb4 update" in your application

**Comment by yeshamavani** [comment]
@Rahulgojra @surabhidwivedi  resolved ?
