### ISSUE TITLE
Cannot read property 'constructor' of null

### ISSUE THREAD

**Issue by leosul** [sourcefuse/loopback4-helmet#25]
**Describe the bug**

**To Reproduce**
To reproduce,
npm uninstall loopback4-helmet

Configure application, put this.component(Loopback4HelmetComponent);

Setup bind
this.bind(HelmetSecurityBindings.CONFIG).to({
            referrerPolicy: {
              policy: 'same-origin',
            },
            contentSecurityPolicy: {
              directives: {
                frameSrc: ["'self'"],
              },
            },
          });

In a sequence constructor
@inject(HelmetSecurityBindings.HELMET_SECURITY_ACTION)
    protected helmetAction: HelmetAction,

Handle
await this.helmetAction(request, response);

When I try to request any endpoint I receive error:
 GET /api/v1/animal/1/10?sort=order&direction=asc failed with status code 500. TypeError: Cannot read property 'constructor' of null

**Expected behavior**

The expectation is to intercept all requests and use this for security, mainly avoiding XSS attacks

**Screenshots**
![image](https://user-images.githubusercontent.com/22174344/150677255-ea870a6b-3c09-459e-a793-6d7e9dac3aa7.png)

@loopback/cli version: 3.0.0

**Comment by whompsprojects** [comment]
I am getting same error in @loopback/context :- 3.18.0 &  "loopback4-helmet": "^3.0.0"

**Comment by whompsprojects** [comment]
Any update guys.. please help me this

**Comment by akshatdubeysf** [comment]
Hi @whompsprojects, can you share your helmetConfig bindings if any?

**Comment by akshatdubeysf** [comment]
This issue seems to be a due to a bug when helmetBindings is missing, if you don't have any specific helmet config, try to pass an empty object to the HelmetConfig binding.
