### ISSUE TITLE
Regd error in request for : await this.helmetAction(request, response);

### ISSUE THREAD

**Issue by surabhidwivedi** [sourcefuse/loopback4-helmet#30]
I am getting error in the following  line 

// Helmet Action here
      await this.helmetAction(request, response);

Argument of type 'import("//node_modules/@types/express/index").Request<import("/home/surabhi/Documents/ /node_modules/@types/express-serve-static-core/index").ParamsDictionary, any, any, qs.ParsedQs, Record<string, any>>' is not assignable to parameter of type 'import /node_modules/@loopback/express/node_modules/@types/express/index").Request<import("//node_modules/@loopback/express/node_modules/@types/express-serve-static-core/index").ParamsDictionary, any, any, qs.ParsedQs, Record<...>>'.
The types of 'app.get' are incompatible between these types.
Type '((name: string) => any) & IRouterMatcher<Application, any>' is not assignable to type '((name: string) => any) & IRouterMatcher<Application<Record<string, any>>, any>'.
Type '((name: string) => any) & IRouterMatcher<Application, any>' is not assignable to type 'IRouterMatcher<Application<Record<string, any>>, any>'.
Types of parameters 'name' and 'path' are incompatible.
Type 'PathParams' is not assignable to type 'string'.
Type 'RegExp' is not assignable to type 'string'.ts(2345)

I appreciate your help.

**Comment by akshatdubeysf** [comment]
You need to import the Request and Response types from @loopback/rest, can you confirm if you have done that? If possible share the sequence file.

**Comment by surabhidwivedi** [comment]
import {inject} from '@loopback/core';
import {FindRoute, InvokeMethod, InvokeMiddleware, ParseParams, Reject, Request, RequestContext, RestBindings, Send, SequenceActions, SequenceHandler} from '@loopback/rest';
import {HelmetAction, HelmetSecurityBindings} from 'loopback4-helmet';
export class MySequence implements SequenceHandler {

  @inject(SequenceActions.INVOKE_MIDDLEWARE, {optional: true})
  protected invokeMiddlewareN: InvokeMiddleware = () => false;


  constructor(
    @inject(SequenceActions.FIND_ROUTE) protected findRoute: FindRoute,
    @inject(SequenceActions.PARSE_PARAMS) protected parseParams: ParseParams,
    @inject(SequenceActions.INVOKE_METHOD) protected invoke: InvokeMethod,
    @inject(SequenceActions.SEND) public send: Send,
    @inject(SequenceActions.REJECT) public reject: Reject,
    @inject(RestBindings.Http.REQUEST) private request: Request,
    @inject(HelmetSecurityBindings.HELMET_SECURITY_ACTION)
    protected helmetAction: HelmetAction,
  ) { }


  async handle(context: RequestContext) {
    const requestTime = Date.now();
    try {

      const {request, response} = context;
      const route = this.findRoute(request);
      const args = await this.parseParams(request, route);
      // const express = require('express');

      // const app: Express = express();


      // Helmet Action here
      await this.helmetAction(request, response);



      const result = await this.invoke(route, args);
      this.send(response, result);
    } catch (err) {
      console.log();
    } finally {
      console.log();
    }
  }
}

**Comment by akshatdubeysf** [comment]
can you also share the versions of loopback4-helmet and @loopback/rest

**Comment by surabhidwivedi** [comment]
Can u pls help me how can I check the versions ?

**Comment by akshatdubeysf** [comment]
You can find the version in your package.json file

**Comment by surabhidwivedi** [comment]
"helmet": "^5.0.2" , "@loopback/rest": "^9.1.1"

Thanks for your help.

**Comment by rohitvishwakarma-sf** [comment]
@surabhidwivedi  please provide "loopback4-helmet" version that you are using. I think you shared the 'helmet' version

**Comment by surabhidwivedi** [comment]
"loopback4-helmet": "^3.0.0"
"@loopback/rest": "^9.1.1"

**Comment by rohitvishwakarma-sf** [comment]
@surabhidwivedi please try latest version of loopback4-helmet

**Comment by surabhidwivedi** [comment]
I changed the version "loopback4-helmet": "^4.0.0"
The error is gone, but If I run the page its not getting loaded and session times out after some time.

**Comment by rohitvishwakarma-sf** [comment]
@surabhidwivedi  can you please share following ?
1.  node version you are using 
2. all the dependencies and devDependencies in your package.json
2. logs in your terminal when you hit npm start

**Comment by surabhidwivedi** [comment]
1- node -v - v14.19.0

2-
 "@loopback/authentication": "^8.0.1",
    "@loopback/authentication-jwt": "^0.10.1",
    "@loopback/boot": "^4.0.1",
    "@loopback/core": "^3.0.1",
    "@loopback/repository": "^4.0.1",
    "@loopback/rest": "^11.0.1",
    "@loopback/rest-crud": "^0.12.1",
    "@loopback/rest-explorer": "^4.0.1",
    "@loopback/service-proxy": "^4.0.1",
    "axios": "^0.21.1",
    "bcrypt": "^5.0.1",
    "config": "^3.3.6",
    "content-security-policy": "^0.3.4",
    "frameguard": "^4.0.0",
    "hsts": "^2.2.0",
    "js-sha512": "^0.8.0",
    "jsonwebtoken": "^8.5.1",
    "loopback": "^3.28.0",
    "loopback-connector-mongodb": "^5.5.0",
    "loopback-connector-openapi": "^6.2.0",
    "loopback4-helmet": "^4.0.0",
    "mongoose": "^5.11.13",
    "multer": "^1.4.2",
    "njwt": "^1.0.0",
    "sh-loopback4-helmet": "^1.0.1",
    "tslib": "^2.0.0",
    "unzip-stream": "^0.3.1",
    "unzipper": "^0.10.11"
  },
  "devDependencies": {
    "@loopback/build": "^8.0.1",
    "@loopback/eslint-config": "^12.0.1",
    "@loopback/testlab": "^4.0.1",
    "@types/bcrypt": "^5.0.0",
    "@types/morgan": "^1.9.2",
    "@types/multer": "^1.4.5",
    "@types/node": "^10.17.60",
    "@types/unzipper": "^0.10.3",
    "eslint": "^8.6.0",
    "source-map-support": "^0.5.21",
    "typescript": "~4.5.4"
  }


3-There is no log in the terminal after npm start

**Comment by rohitvishwakarma-sf** [comment]
@surabhidwivedi  so when do you get the error ? On hitting the API ?

**Comment by rohitvishwakarma-sf** [comment]
> I changed the version "loopback4-helmet": "^4.0.0" The error is gone, but If I run the page its not getting loaded and session times out after some time.

Which page ?

**Comment by surabhidwivedi** [comment]
after I start npm start, its showing as stated in console but not loading in browser.

**Comment by surabhidwivedi** [comment]
yes

**Comment by rohitvishwakarma-sf** [comment]
@surabhidwivedi  Then which URL is not opening in the browser ?

**Comment by surabhidwivedi** [comment]
the URL which I am using for this code. 
My code works otherwise but after using helmet as per https://github.com/sourcefuse/loopback4-helmet session gets time out and page doesn't load.

**Comment by rohitvishwakarma-sf** [comment]
can you please provide following ?
1. Exact URL you are hitting on browser
2. Screenshots of the browser console, when the session times out

**Comment by surabhidwivedi** [comment]
![image](https://user-images.githubusercontent.com/27663178/156355405-1aaf576f-b588-475d-9efd-377a8b1e7ab7.png)

![image](https://user-images.githubusercontent.com/27663178/156355594-7b468c1e-9fca-4766-9bf9-c6bd41f6dd58.png)

**Comment by rohitvishwakarma-sf** [comment]
Hey @surabhidwivedi I'm not able to reproduce the issue. Can you please recreate the issue in a repo and share with us ?
