### ISSUE TITLE
Can not import component

### ISSUE THREAD

**Issue by dangmiracle** [sourcefuse/loopback4-helmet#4]
Can not import component to lb4 application.Please help
<img width="968" alt="Screenshot 2020-12-15 at 4 00 54 AM" src="https://user-images.githubusercontent.com/17794078/102135153-227da280-3e8a-11eb-89c9-bbbe1fb2b68b.png">

**Comment by akshatdubeysf** [comment]
@dangmiracle can you share the error/issue you are facing, possibly with a screenshot or stacktrace?

**Comment by akshatdubeysf** [comment]
@dangmiracle share the LB4 version you are using along with package version you are using.

**Comment by abjagtap** [comment]
facing same issue

**Comment by akshatdubeysf** [comment]
Can anyone of @dangmiracle, @HarshalNathe or @abjagtap share the version of @loopback/context used

**Comment by HarshalNathe** [comment]
@akshatdubeysf I'm using the **^3.15.0** version of **@loopback/context**

**Comment by akshatdubeysf** [comment]
@HarshalNathe the latest version of loopback4-helmet works with 3.18.0, and there seems to be some typing incompatibility between these two versions from the Loopback package, you can try updating your context package to 3.18.0

**Comment by arnaud16571542** [comment]
I confirm : Doesn't work with @loopback/context 4.0.0. Work better with 3.18.0

**Comment by markus-hsk** [comment]
Is there a solution, or at least a plan for fixing this?

**Comment by akshatdubeysf** [comment]
HI @markus-hsk , the helmet package has been updated, you can try the latest version, which works with @loopback/context 5.0.0.

**Comment by markus-hsk** [comment]
Thank you @akshatdubeysf , works!

**Comment by Rahulgojra** [comment]
Hi @akshatdubeysf 
I have to configure loopback4-helmet in my application, when I am trying to add component in application.js, I am facing same issue and I have tried all the solution which you discussed above. Please help me on this 
versions:-
 "@loopback/boot": "^3.4.2",
    "@loopback/context": "^5.0.0",
    "@loopback/core": "^2.16.2",
    "@loopback/repository": "^3.7.1",
    "@loopback/rest": "^10.0.0",
    "@loopback/rest-explorer": "^3.3.2",
    "@loopback/service-proxy": "^3.2.2",
 "loopback-connector-rest": "^4.0.1",
    "loopback4-helmet": "^4.2.0",

Error: Argument of type 'typeof Loopback4HelmetComponent' is not assignable to parameter of type 'Constructor<Component>'.
  Types of construct signatures are incompatible.
    Type 'new () => Loopback4HelmetComponent' is not assignable to type 'new (...args: any[]) => Component'.
      Construct signature return types 'Loopback4HelmetComponent' and 'Component' are incompatible.
        The types of 'bindings' are incompatible between these types.

**Comment by yeshamavani** [comment]
@Rahulgojra make sure you are using correct version of @loopback/context
