### ISSUE TITLE
Cross origin Error in Application, but api-explorer works fine

### ISSUE THREAD

**Issue by whompsprojects** [sourcefuse/loopback4-helmet#48]
**Describe the bug**
Cross origin Error in Application, but api-explorer works fine

**To Reproduce**
1.  In application.ts file :- 
this.bind(HelmetSecurityBindings.CONFIG).to({
  referrerPolicy: {
    policy: 'same-origin',
  },
  contentSecurityPolicy: {
    directives: {
      frameSrc: ["'self'"],
    },
  },
});

2. Also throw has been blocked by CORS policy: Response header

**Comment by akshatdubeysf** [comment]
Are you getting this CORS error from Swagger/Api Explorer? Can you share the exact error message?
