### ISSUE TITLE
Update the docs: how to use this with LB4 Middleware Sequence?

### ISSUE THREAD

**Issue by gtamas** [sourcefuse/loopback4-helmet#5]
**Is your feature request related to a problem? Please describe.**

Your documentation is outdated. It still assumes people use the Action based sequence, but that's deprecated. The LB4 CLI generates Middleware sequences now, but you don't have instructions for that. 

**Describe the solution you'd like**

Please provide up-to-date instruction on how to use this with Loopback 4. How to use this component in a Middleware sequence?
The LB4 documentation on this is insufficient and confusing.

**Describe alternatives you've considered**

**Additional context**

**Comment by akshatdubeysf** [comment]
related to [this](https://github.com/sourcefuse/loopback4-ratelimiter/issues/11#issuecomment-840431599).

**Comment by samarpan-b** [comment]
It does not support middleware type binding. For using as middleware you can directly use express middleware library.
But it's a good feature request.

Would you care to contribute for it ? @gtamas
