### ISSUE TITLE
TypeError: Cannot read property 'constructor' of null

### ISSUE THREAD

**Issue by Rahulgojra** [sourcefuse/loopback4-helmet#65]
Sequence.ts file: 
![image](https://user-images.githubusercontent.com/67505192/216979892-4f60c84d-5349-4adf-a9dc-48ec47e4b307.png)

at console err, it is giving me this error,
anyone have idea about that

**Comment by yeshamavani** [comment]
@Rahulgojra can you share the detailed error.

**Comment by Rahulgojra** [comment]
Hi @yeshamavani 
this is the exact error which I get when I am trying to call the endpoint 
![image](https://user-images.githubusercontent.com/67505192/217182553-f94717a2-d3f3-4afc-8925-b05765388de2.png)

application.ts
![image](https://user-images.githubusercontent.com/67505192/217183756-2e5489f5-375c-4f66-b933-1a14f3e5e92e.png)

**Comment by yeshamavani** [comment]
@Rahulgojra  have you installed helmet as a dependency in your application

**Comment by Rahulgojra** [comment]
@yeshamavani yes I installed it

**Comment by Rahulgojra** [comment]
@yeshamavani 
![image](https://user-images.githubusercontent.com/67505192/217238043-c0ce26ba-c626-41ee-86f1-2718c1dab155.png)

**Comment by yeshamavani** [comment]
![image](https://user-images.githubusercontent.com/83634146/217238296-6602567f-a390-4265-93bb-b6cf70c3f8df.png)
@Rahulgojra please use this version

**Comment by Rahulgojra** [comment]
@yeshamavani still getting the same problem 
I just followed the these steps only for configure the helmet in my application
https://github.com/sourcefuse/loopback4-helmet

**Comment by Rahulgojra** [comment]
@yeshamavani I updated my application to lb4, still I am getting the same error

**Comment by yeshamavani** [comment]
@Rahulgojra are you still facing the issue.
